import Head from 'next/head'
import styles from '../styles/Home.module.css'
import StudyToUkraine from '../src/studyToUkraine'
import isObjectNull from "../isObjectNull";
import client from "../client";

export default function Home(props) {
  const {
      studyToUkraineProps
  }  = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>الدراسة في أوكرانيا</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <StudyToUkraine study={studyToUkraineProps}/>
    </div>
  )
}

export async function getServerSideProps(context){
    var data_home = await client.fetch("*[_id=='home'][0]{titreStudyInUkraine,titreAdmission}");
    const studyToUkraineProps = {
        titreStudyInUkraine:isObjectNull(data_home.titreStudyInUkraine),
        titreAdmission:isObjectNull(data_home.titreAdmission),
    }
    return {
      props: {
        studyToUkraineProps,
      },
    }
}